### Generate code to read files created by MarkSim climate datasets ###
###

# Index is a column FDID (Folder_ID). The first digits are the folder (e.g. "fold-01"), the next 4 digits correspond
# to the point (e.g. "0001")

# Are 181.836 points are generated by MarkSim, but not all the points are correctly, so for some points not
# generate outputs

# This code identifies the pixels that contain climate for Colombian Orinoquia and then link with the information
# generated by MarkSim

## Packages

############################## Make path climate ##############################

library(raster)
library(snowfall)
library(data.table)

## Library for works in parallel. 
library(foreach)
library(doSNOW)   ## For Windows and if you use Linux, you should doMC library


scenario <- 'rcp45'  ## Shift between baseline, rcp26, rcp45 or rcp85

## make the path for the main directory
path <- '//dapadfs/workspace_cluster_6/ALPACAS/Plan_Regional_de_Cambio_Climatico_Orinoquia/'

## directory with contains the raster for the Orinoquia
sub_dir_climate <- '01-datos_clima/datos_diarios/_dat_files/'  ## Folder with contains the raster for the Orinoquia

## the name for the file

name_raster_id <- 'coords_id.tif' ## Raster
name_txt_id <- 'coords_id.txt'    ## Data Base (Similiar to the raster)


id_txt_climate <- read.table(paste0(path, sub_dir_climate, name_txt_id), header = T) ## Data Base with the attributes


id_txt_climate[, 1:2] <- datos[, 1:2]  ## Change for the coordinates of the raster
colnames(id_txt_climate[, 1:2]) <- c('LONGITUD', 'LATITUD')  ## naming the coordinates

sfInit(parallel = T, cpus = 25) #initiate cluster


#export functions for works in paralell 

sfSource(file = 'C:/R_Projects/DSSAT_use_Marksim/main_functions.R')


id_for_choose <- sfLapply(id_txt_climate$FDID, FUN = makeDir_id, 4)
id_for_choose <- rbindlist(id_for_choose)


id_for_choose <- data.frame(id_for_choose, longitude = id_txt_climate$LONGITUD, latitude = id_txt_climate$LATITUD)

# Make a text file (.txt) with the identifier of the pixel in the position of raster for MarkSim's datasets


sfExport('path')
sfExport('id_for_choose')
sfExport('scenario')

path_daily_data <- sfSapply(1:dim(id_for_choose)[1], function(i) paste0(path, '/01-datos_clima/datos_diarios/', scenario,'/fold-', id_for_choose[i, 1], '/', id_for_choose[i, 2]))

id_for_choose <- data.frame(id_for_choose, path = path_daily_data)


write.table(id_for_choose, file = paste0(path, '/01-datos_clima/datos_diarios/', scenario, '/coords_path.txt'), sep = ";", row.names = F)


sfStop()

